apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: kubevela-demo-app
spec:
  components:
    - name: kubevela-demo-app-web
      type: webservice
      properties:
        image: cnych/kubevela-demo-cicd-app
        imagePullPolicy: Always
        port: 8080
      traits:
        - type: scaler
          properties:
            replicas: 5
        - type: labels
          properties:
            jenkins-build-commit: GIT_COMMIT
        - type: gateway
          properties:
            domain: kubevela-demo-cicd-app.k8s.local
            http:
              "/": 8088
